version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "docker/noetic/" # Location of package manifests
    schedule:
      interval: "weekly"