# This Dockerfile is the base image for Mov.ai - Based on Ubuntu 22.04
FROM ubuntu:22.04 AS base

# Labels
LABEL description="MOV.AI Base Image"
LABEL maintainer="devops@mov.ai"

# Arguments
ARG USER_ID=1000
ARG APT_REPOSITORY="https://artifacts.aws.cloud.mov.ai/repository"

### Environment config
ENV MOVAI_HOME="/opt/mov.ai" \
    ROS_VERSION="humble" \
    ROS_DISTRO="humble"

ENV APP_PATH="${MOVAI_HOME}/app" \
    APP_LOGS="${MOVAI_HOME}/logs" \
    APP_UPDATES="${MOVAI_HOME}/updates" \
    USER_ID=${USER_ID}

# Create Default User and copy default settings
RUN adduser --uid ${USER_ID} --home ${MOVAI_HOME} --disabled-password --gecos '' movai

COPY --chown=movai:movai files/bashrc.bash ${MOVAI_HOME}/.bashrc
COPY --chown=movai:movai files/welcome ${MOVAI_HOME}/.welcome

# Copy build scripts
COPY files/user-provision.sh /usr/local/bin/
COPY files/install-packages.sh /usr/local/bin/
COPY --chown=movai:movai files/deploy.sh /usr/local/bin/deploy.sh

# Copy startup files
COPY files/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
COPY files/movai-entrypoint.sh /usr/local/bin/movai-entrypoint.sh

# Install base packages
COPY files/packages.bash /tmp/packages.bash
COPY docker/$ROS_VERSION/packages.apt /tmp/packages.apt

# Install requirements for ppa certificates registration
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
    apt-get update &&\
    apt-get install -y curl gnupg ca-certificates --no-install-recommends

# Update APT sources with MOV.AI proxies (humble/jammy)
# COPY files/apt/movai-ubuntu-archive-proxy.list /etc/apt/sources.list.d/movai-ubuntu-archive-proxy.list
# COPY files/apt/movai-ubuntu-ports-proxy.list /etc/apt/sources.list.d/movai-ubuntu-ports-proxy.list
# COPY files/apt/movai-ubuntu-security-proxy.list /etc/apt/sources.list.d/movai-ubuntu-security-proxy.list
# SHELL ["/bin/bash", "-o", "pipefail", "-c"]
# RUN mv /etc/apt/sources.list /etc/apt/sources.list.bck &&\
#    touch /etc/apt/sources.list &&\
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -fsSL $APT_REPOSITORY/movai-applications/gpg | apt-key add -  &&\
    if [ "$(uname -m)" = "x86_64" ] ; then rm -f /etc/apt/sources.list.d/movai-ubuntu-ports-proxy.list ; fi &&\
    if [ "$(uname -m)" = "aarch64" ] || [ "$(uname -m)" = "armv7l" ] ; then rm -f /etc/apt/sources.list.d/movai-ubuntu-archive* && rm -f /etc/apt/sources.list.d/movai-ubuntu-security* ; fi &&\
    apt-get update && apt-get upgrade -y &&\
    /usr/local/bin/install-packages.sh &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/* &&\
    rm -rf /var/log/*

# Run user provision
COPY files/user.rc /tmp/user.rc
RUN /usr/local/bin/user-provision.sh

SHELL ["/bin/bash", "-c"]
WORKDIR ${APP_PATH}
ENTRYPOINT [ "docker-entrypoint.sh" ]

FROM base AS jammy-python38
ENV PYTHON_VERSION=3.8 \
    PIP_PACKAGE_REPO="https://artifacts.cloud.mov.ai/repository/pypi-experimental/simple" \
    PPA_REPOSITORY="ppa:deadsnakes/ppa"

USER root
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -fsSL https://artifacts.cloud.mov.ai/repository/movai-applications/gpg | apt-key add - && \
    add-apt-repository ppa:deadsnakes/ppa && \
    add-apt-repository "${PPA_REPOSITORY}" && \
    apt-get update > /dev/null && \
    apt-get install -y --no-install-recommends software-properties-common "${PYTHON_VERSION}" "${PYTHON_VERSION}-distutils" && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | ${PYTHON_VERSION} - && \
    apt-get clean -y > /dev/null && \
    rm -rf /var/cache/apt/* && \
    rm -rf /var/lib/apt/lists/*

USER movai
